#!/bin/bash
BN=`basename $1`
echo "$BN"
(
  for f in `ls ../logs/$1/ | grep -P '\d+'`
    do
      echo -n "$f "
      RD=`./analyze "../logs/$1/$f/" \
        | grep ratio \
        | sed 's/^.*: //'`
      RAT=`echo "$RD" | sed 's/%.*//'`
      REM=`echo "$RD" | sed 's/.*% (\([0-9]*\) published, \([0-9]*\) received, \([0-9]*\) aggregated)/\1-\3-\2/' | bc`
      echo -e "scale = 5\nprint $RAT/100" | bc
      echo " $REM"
    done
) \
| sort -n \
| column -t \
| tee $BN.ratios.dat
